# Generated by Django 4.2.30 on 2026-07-10 10:33

from django.db import migrations, models


def normalize_ordering(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    Module = apps.get_model('courses', 'Module')
    Lesson = apps.get_model('courses', 'Lesson')

    for course in Course.objects.all().iterator():
        modules = Module.objects.filter(course=course).order_by(
            'order',
            'created_at',
            'id',
        )
        for index, module in enumerate(modules, start=1):
            if module.order != index:
                Module.objects.filter(pk=module.pk).update(order=index)

    for module in Module.objects.all().iterator():
        lessons = Lesson.objects.filter(module=module).order_by(
            'order',
            'created_at',
            'id',
        )
        for index, lesson in enumerate(lessons, start=1):
            if lesson.order != index:
                Lesson.objects.filter(pk=lesson.pk).update(order=index)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_module_lesson'),
    ]

    operations = [
        migrations.RunPython(normalize_ordering, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='unique_lesson_order_per_module'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_module_order_per_course'),
        ),
    ]
