# Generated by Django 4.2.30 on 2026-07-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=500)),
                ('video_id', models.CharField(max_length=50)),
                ('video_title', models.CharField(max_length=500)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-cached_at'],
            },
        ),
    ]
